language: python
python:
- 2.7
- 3.3
- 3.4
before_install:
  - pip install codecov
install:
  - pip install -r requirements.txt -r test-requirements.txt
script: nosetests
after_success:
  - codecov
services:
  - cassandra
