language: python
python:
- 2.7
- pypy
- 3.3
- 3.4
before_install:
  - pip install codecov
install:
  - pip install -r requirements.txt -r test-requirements.txt
script: nosetests
after_success:
  - covercov
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: johnb
  password:
    secure: "Q0XIvK1R4kv2uFoUDOARQ1swgcnWqlE0jO20Urc0RsuTejY4/uNgUxvp3wfnd+NKARHwrUQFYHGzI5ueVcppQzGzZArr/o3DB9Vh7OURBtbqrSReRsz9QXmV3pDAbSq3p1QbhCryZeEOU0V5DqlnYfVuiM27WWo+V8gg20qn5OY="
  on:
    python: 2.7
    tags: true
    all_branches: true
services:
  - cassandra
